import { z } from "zod";
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { api, jsonResult, errorResult } from "../client.js";

/**
 * Register reflection tools (bot self-learning reflections)
 */
export function registerReflectionsTools(server: McpServer): void {
  // 1. List Reflections
  server.registerTool(
    "neuron_list_reflections",
    {
      title: "List Reflections",
      description: "List self-learning reflections generated by a bot, optionally filtered by status",
      inputSchema: z.object({
        botId: z.string().describe("The ID of the bot to list reflections for"),
        status: z.enum(["pending", "approved", "rejected"]).optional().describe("Filter by reflection status"),
      }),
      annotations: {
        openWorldHint: true,
      },
    },
    async (args) => {
      const { botId, status } = args;
      const params: Record<string, string> = {};

      if (status !== undefined) {
        params.status = status;
      }

      const response = await api("GET", `/reflections/bot/${botId}`, undefined, params);

      if (response.success) {
        return jsonResult(response.data);
      } else {
        return errorResult(response.error || "Failed to list reflections");
      }
    }
  );

  // 2. Approve Reflection
  server.registerTool(
    "neuron_approve_reflection",
    {
      title: "Approve Reflection",
      description: "Approve a bot reflection to incorporate it into the bot's learning and behavior",
      inputSchema: z.object({
        id: z.string().describe("The ID of the reflection to approve"),
      }),
      annotations: {
        openWorldHint: true,
      },
    },
    async (args) => {
      const response = await api("PUT", `/reflections/${args.id}/approve`);

      if (response.success) {
        return jsonResult(response.data || { message: "Reflection approved successfully" });
      } else {
        return errorResult(response.error || "Failed to approve reflection");
      }
    }
  );

  // 3. Reject Reflection
  server.registerTool(
    "neuron_reject_reflection",
    {
      title: "Reject Reflection",
      description: "Reject a bot reflection to prevent it from being incorporated into the bot's behavior",
      inputSchema: z.object({
        id: z.string().describe("The ID of the reflection to reject"),
      }),
      annotations: {
        openWorldHint: true,
      },
    },
    async (args) => {
      const response = await api("PUT", `/reflections/${args.id}/reject`);

      if (response.success) {
        return jsonResult(response.data || { message: "Reflection rejected successfully" });
      } else {
        return errorResult(response.error || "Failed to reject reflection");
      }
    }
  );

  // 4. Sync Reflections
  server.registerTool(
    "neuron_sync_reflections",
    {
      title: "Sync Reflections",
      description: "Synchronize and update the bot's knowledge base with all approved reflections",
      inputSchema: z.object({
        botId: z.string().describe("The ID of the bot to sync reflections for"),
      }),
      annotations: {
        openWorldHint: true,
      },
    },
    async (args) => {
      const response = await api("POST", `/reflections/bot/${args.botId}/sync`);

      if (response.success) {
        return jsonResult(response.data || { message: "Reflections synced successfully" });
      } else {
        return errorResult(response.error || "Failed to sync reflections");
      }
    }
  );
}
